Repository oamg/convert2rhel, pull requests merged in 2023-01, with the labels that each got.

#672 [RHELC-823] chore: add devcontainer
  .devcontainer/.bashrc
  .devcontainer/centos8-development.Dockerfile
  .devcontainer/centos8.requirements.txt
  .devcontainer/devcontainer.json
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  CONTRIBUTING.md
Labels: no-changelog

#685 [RHELC-598] Fix for check-user-response test
  tests/integration/tier0/check-user-response/test_user_response.py
Labels: no-changelog

#682 [RHELC-839] Port the cert unittests to use pytest instead of unittest.
  convert2rhel/unit_tests/cert_test.py
Labels: no-changelog

#699 [RHELC-858] Remove configs for RHEL6
  convert2rhel/data/6/x86_64/configs/centos-6-x86_64.cfg
  convert2rhel/data/6/x86_64/configs/oracle-6-x86_64.cfg
  convert2rhel/data/6/x86_64/configs/suse_es-6-x86_64.cfg
  convert2rhel/data/6/x86_64/rhel-certs/69.pem
  convert2rhel/systeminfo.py
  convert2rhel/unit_tests/cert_test.py
  convert2rhel/unit_tests/conftest.py
Labels: enhancement

#695 Remove black args from pre-commit-config file
  .pre-commit-config.yaml
  convert2rhel/main.py
  pyproject.toml
Labels: no-changelog

#690 [RHELC-399] test: add description for single yum transaction
  tests/integration/tier1/single-yum-transaction/main.fmf
Labels: no-changelog

#705 [RHELC-862] chore: Separate make fetch-images
  .gitignore
  Makefile
Labels: no-changelog

#689 [RHELC-399] test: add description for yum distro-sync
  tests/integration/tier1/yum-distro-sync/main.fmf
  tests/integration/tier1/yum-distro-sync/test_yum_distro_sync.py
Labels: no-changelog

#700 [RHELC-864] refactor: Rename Docker to container
  .devcontainer/devcontainer.json
  .github/renovate.json
  CONTRIBUTING.md
  Containerfiles/centos7.Containerfile
  Containerfiles/centos8.Containerfile
  Containerfiles/rpmbuild.centos7.Containerfile
  Containerfiles/rpmbuild.centos8.Containerfile
  Makefile
  convert2rhel/unit_tests/README.md
Labels: no-changelog

#693 [RHELC-399] Add description for integration tests
  tests/integration/tier0/latest-kernel-check/main.fmf
  tests/integration/tier0/sub-man-rollback/main.fmf
  tests/integration/tier1/convert-offline-systems/main.fmf
  tests/integration/tier1/removed-pkgs-centos-85/main.fmf
  tests/integration/tier1/resolve-dependency/main.fmf
Labels: no-changelog

#702 [KAIZEN] Make pylint logs usable
  .github/workflows/pylint.yml
  .pre-commit-config.yaml
  .pylintrc
  Makefile
  convert2rhel/utils.py
  requirements/centos7.requirements.txt
  requirements/centos8.requirements.txt
  scripts/run_lint.sh
  tests/integration/tier1/checks-after-conversion/test_enabled_repositories.py
Labels: no-changelog

#615 [RHELC-745] Fix conversion with "LANGUAGE" envar
  .pylintrc
  convert2rhel/unit_tests/utils_test.py
  convert2rhel/utils.py
  tests/integration/tier1/set-locale/use_non_english_language.py
Labels: bug-fix

#613 [RHELC-244] allowing the overriding of kmod inhibitors
  convert2rhel/checks.py
  convert2rhel/unit_tests/checks_test.py
Labels: enhancement
