Repository oamg/convert2rhel, pull requests merged in 2023-02, with the labels that each got.

#668 [RHELC-776] Remove shim-x64 special workaround
  convert2rhel/main.py
  convert2rhel/special_cases.py
  convert2rhel/unit_tests/main_test.py
  convert2rhel/unit_tests/special_cases_test.py
  plans/tier1.fmf
  tests/integration/tier1/handle-special-pkgs-case/main.fmf
  tests/integration/tier1/handle-special-pkgs-case/test_handle_shim_x64_pkg.py
Labels: enhancement

#692 [RHELC-399] Document int tests
  tests/integration/tier1/remove-all-submgr-pkgs/main.fmf
  tests/integration/tier1/system-up-to-date/main.fmf
Labels: no-changelog

#691 [RHELC-399] Describe the "checks after conversion" test
  tests/integration/tier1/checks-after-conversion/main.fmf
Labels: no-changelog

#686 [RHELC-836] Improve release notes
  .github/release.yml
Labels: no-changelog

#714 [RHELC-887] chore: require rebase on push
  .pre-commit-config.yaml
Labels: no-changelog

#681 [RHELC-723] Remove RegistrationCommand.args property
  convert2rhel/subscription.py
  convert2rhel/unit_tests/subscription_test.py
Labels: enhancement

#694 [RHELC-399] Add test description
  tests/integration/tier1/changed-grub-file/main.fmf
  tests/integration/tier1/method/main.fmf
  tests/integration/tier1/os-release-removal/main.fmf
  tests/integration/tier1/os-release-removal/remove_os_release.py
Labels: no-changelog

#563 [RHELC-693] Check if org and key passed
  convert2rhel/toolopts.py
  convert2rhel/unit_tests/toolopts_test.py
Labels: enhancement

#671 [RHELC-780] Improve logging and handling of RHSM facts
  convert2rhel/breadcrumbs.py
  convert2rhel/unit_tests/breadcrumbs_test.py
Labels: enhancement

#733 [RHELC-693] test: remove unnecessary code for org and key
  convert2rhel/subscription.py
  convert2rhel/unit_tests/subscription_test.py
  tests/integration/tier0/check-user-response/test_user_response.py
  tests/integration/tier0/test-check-rollback-handling/test_check_rollback_handling.py
Labels: no-changelog

#722 [RHELC-882] Change the label for FILE output to DEBUG.
  convert2rhel/logger.py
  convert2rhel/unit_tests/utils_test.py
Labels: enhancement

#669 [RHELC-779] Remove unused function call_yum_cmd_w_downgrades
  convert2rhel/pkghandler.py
  convert2rhel/pkgmanager/handlers/dnf.py
  convert2rhel/pkgmanager/handlers/yum.py
  convert2rhel/unit_tests/pkghandler_test.py
Labels: enhancement

#709 [RHELC-778] Add progress indicators for YUM and DNF modules
  convert2rhel/pkgmanager/__init__.py
  convert2rhel/pkgmanager/handlers/dnf/__init__.py
  convert2rhel/pkgmanager/handlers/dnf/callback.py
  convert2rhel/pkgmanager/handlers/yum/__init__.py
  convert2rhel/pkgmanager/handlers/yum/callback.py
  convert2rhel/unit_tests/conftest.py
  convert2rhel/unit_tests/pkgmanager/handlers/dnf/__init__.py
  convert2rhel/unit_tests/pkgmanager/handlers/dnf/callback_test.py
  convert2rhel/unit_tests/pkgmanager/handlers/dnf/dnf_test.py
  convert2rhel/unit_tests/pkgmanager/handlers/yum/__init__.py
  convert2rhel/unit_tests/pkgmanager/handlers/yum/callback_test.py
  convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py
  setup.py
Labels: enhancement

#724 [RHELC-134] Refactor yum makecache to be separate from main checks
  convert2rhel/main.py
  convert2rhel/pkghandler.py
  convert2rhel/pkgmanager/__init__.py
  convert2rhel/unit_tests/main_test.py
  convert2rhel/unit_tests/pkghandler_test.py
  convert2rhel/unit_tests/pkgmanager/pkgmanager_test.py
  convert2rhel/unit_tests/repo_test.py
  tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py
Labels: enhancement

#653 [RHELC-785] Add system_release and prompt_ammount as envar
  .packit.yaml
  plans/main.fmf
  plans/tier0.fmf
  plans/tier1.fmf
  plans/tier2.fmf
  tests/integration/conftest.py
  tests/integration/tier0/backup-release/test_backup_release.py
  tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py
  tests/integration/tier0/custom-kernel/test_custom_kernel.py
  tests/integration/tier0/inhibit-if-kmods-is-not-supported/main.fmf
  tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py
  tests/integration/tier0/inhibit-if-oracle-system-uses-not-standard-kernel/test_oracle_bad_kernel.py
  tests/integration/tier0/latest-kernel-check/test_latest_kernel_check.py
  tests/integration/tier0/releasever-as-mapping/test_releasever_as_mapping.py
  tests/integration/tier0/sub-man-rollback/test_sub_man_rollback.py
  tests/integration/tier0/test-check-rollback-handling/main.fmf
  tests/integration/tier0/test-check-rollback-handling/test_check_rollback_handling.py
  tests/integration/tier1/changed-grub-file/test_invalid_changed_grub.py
  tests/integration/tier1/changed-grub-file/test_valid_changed_grub.py
  tests/integration/tier1/changed-yum-conf/test_patch_yum_conf.py
  tests/integration/tier1/checks-after-conversion/test_enabled_repositories.py
  tests/integration/tier1/config-file/test_config_file.py
  tests/integration/tier1/convert-offline-systems/run_conversion.py
  tests/integration/tier1/method/activation_key.py
  tests/integration/tier1/method/rhsm.py
  tests/integration/tier1/method/rhsm_non_eus.py
  tests/integration/tier1/method/satellite.py
  tests/integration/tier1/one-kernel-scenario/install_one_kernel.py
  tests/integration/tier1/one-kernel-scenario/main.fmf
  tests/integration/tier1/one-kernel-scenario/run_conversion.py
  tests/integration/tier1/remove-all-submgr-pkgs/main.fmf
  tests/integration/tier1/remove-all-submgr-pkgs/test_no_submgr_pkg_installed.py
  tests/integration/tier1/remove-all-submgr-pkgs/test_submgr_pkg_installed.py
  tests/integration/tier1/remove-excld-pkgs/test_remove_excld_pkgs.py
  tests/integration/tier1/removed-pkgs-centos-85/main.fmf
  tests/integration/tier1/removed-pkgs-centos-85/test_removed_pkgs_centos_85.py
  tests/integration/tier1/resolve-dependency/install_dependency_packages.py
  tests/integration/tier1/satellite_non_eus_repos/satellite_non_eus_repos.py
  tests/integration/tier1/set-locale/use_non_english_language.py
  tests/integration/tier1/single-yum-transaction/install_multilib_packages.py
  tests/integration/tier1/single-yum-transaction/install_ntp_and_remove_dependency.py
  tests/integration/tier1/single-yum-transaction/remove_excld_pkgs_from_config.py
  tests/integration/tier1/single-yum-transaction/test_single_yum_transaction.py
  tests/integration/tier1/system-up-to-date/install_non_latest_kernel.py
  tests/integration/tier1/system-up-to-date/test_non_latest_kernel_inhibitor.py
  tests/integration/tier1/system-up-to-date/test_system_up_to_date.py
  tests/integration/tier1/yum-distro-sync/install_problematic_package.py
  tests/integration/tier1/yum-distro-sync/test_yum_distro_sync.py
Labels: no-changelog

#710 [RHELC-854] Man/help page to mention config file location
  convert2rhel/toolopts.py
Labels: enhancement

#712 [RHELC-733] Fixes the bug for converting when trying to add in an new UEFI bootloader entry for RHEL
  convert2rhel/grub.py
  convert2rhel/unit_tests/grub_test.py
  plans/tier1.fmf
  tests/integration/tier1/detect-bootloader-partition/main.fmf
  tests/integration/tier1/detect-bootloader-partition/test_detect_correct_boot_partition.py
Labels: bug-fix

#677 [RHELC-828] Add missing integration tests for single yum transaction
  convert2rhel/pkgmanager/handlers/yum/__init__.py
  convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py
  plans/tier0.fmf
  tests/integration/tier0/single-yum-transaction-validation/main.fmf
  tests/integration/tier0/single-yum-transaction-validation/test_single_yum_transaction_validation.py
  tests/integration/tier1/single-yum-transaction/main.fmf
Labels: enhancement

#697 [RHELC-399] Add test description
  tests/integration/tier1/changed-yum-conf/main.fmf
  tests/integration/tier1/config-file/main.fmf
  tests/integration/tier1/one-kernel-scenario/main.fmf
Labels: no-changelog

#721 [RHELC-752] Check for kernel boot files after conversion
  convert2rhel/checks.py
  convert2rhel/grub.py
  convert2rhel/main.py
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/checks_test.py
  convert2rhel/unit_tests/grub_test.py
  convert2rhel/unit_tests/main_test.py
  plans/tier1.fmf
  tests/integration/conftest.py
  tests/integration/tier1/checks-after-conversion/main.fmf
  tests/integration/tier1/checks-after-conversion/test_delete_temp_folder.py
  tests/integration/tier1/checks-after-conversion/test_enabled_repositories.py
  tests/integration/tier1/checks-after-conversion/test_flag_system_as_converted.py
  tests/integration/tier1/checks-after-conversion/test_release_version.py
  tests/integration/tier1/checks-after-conversion/test_rhel_kernel.py
  tests/integration/tier1/checks-after-conversion/test_verify_strings_in_log.py
  tests/integration/tier1/checks-after-conversion/test_yum_check.py
  tests/integration/tier1/kernel-boot-files/main.fmf
  tests/integration/tier1/kernel-boot-files/test_handle_corrupted_files.py
  tests/integration/tier1/kernel-boot-files/test_handle_missing_boot_files.py
Labels: bug-fix

#735 [RHELC-244] Verify overriding usupported kernel module inhibition
  tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py
Labels: no-changelog

#723 [RHELC-849, RHELC-850] Inform+disable telemetry
  convert2rhel/breadcrumbs.py
  convert2rhel/main.py
  convert2rhel/subscription.py
  convert2rhel/unit_tests/breadcrumbs_test.py
  convert2rhel/unit_tests/main_test.py
  convert2rhel/unit_tests/subscription_test.py
  plans/tier1.fmf
  tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py
  tests/integration/tier0/check-internet-connection/test_internet_connection.py
  tests/integration/tier0/custom-kernel/test_custom_kernel.py
  tests/integration/tier0/inhibit-if-kmods-is-not-supported/main.fmf
  tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py
  tests/integration/tier0/latest-kernel-check/test_latest_kernel_check.py
  tests/integration/tier0/test-check-rollback-handling/main.fmf
  tests/integration/tier1/checks-after-conversion/main.fmf
  tests/integration/tier1/checks-after-conversion/test_disable_data_collection.py
  tests/integration/tier1/method/activation_key.py
  tests/integration/tier1/method/custom_repos.py
  tests/integration/tier1/method/main.fmf
  tests/integration/tier1/method/rhsm.py
  tests/integration/tier1/method/rhsm_non_eus.py
  tests/integration/tier1/method/satellite.py
  tests/integration/tier1/remove-all-submgr-pkgs/main.fmf
  tests/integration/tier1/system-up-to-date/test_system_up_to_date.py
Labels: enhancement

#742 Bump version to 1.2
  convert2rhel/__init__.py
  packaging/convert2rhel.spec
Labels: no-changelog
