Repository oamg/convert2rhel, pull requests merged in 2023-07, with the labels that each got.

#855 [RHELC-1061, RHELC-1060, RHELC-1062] Allow package names with periods
  convert2rhel/pkgmanager/handlers/dnf/__init__.py
  plans/rerun.fmf
  pytest.ini
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
Labels: bug-fix

#861 Release v1.3.2
  convert2rhel/__init__.py
  packaging/convert2rhel.spec
Labels: no-changelog

#841 [RHELC-1042] Updates to the action framework
  convert2rhel/actions/__init__.py
  convert2rhel/actions/pre_ponr_changes/backup_system.py
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/actions/pre_ponr_changes/kernel_modules.py
  convert2rhel/actions/pre_ponr_changes/subscription.py
  convert2rhel/actions/pre_ponr_changes/transaction.py
  convert2rhel/actions/report.py
  convert2rhel/actions/system_checks/convert2rhel_latest.py
  convert2rhel/actions/system_checks/custom_repos_are_valid.py
  convert2rhel/actions/system_checks/dbus.py
  convert2rhel/actions/system_checks/efi.py
  convert2rhel/actions/system_checks/is_loaded_kernel_latest.py
  convert2rhel/actions/system_checks/readonly_mounts.py
  convert2rhel/actions/system_checks/rhel_compatible_kernel.py
  convert2rhel/actions/system_checks/tainted_kmods.py
  convert2rhel/main.py
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/actions/actions_test.py
  convert2rhel/unit_tests/actions/data/stage_tests/all_status_actions/test.py
  convert2rhel/unit_tests/actions/data/stage_tests/good_deps_failed_actions/test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/special_cases_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/transaction_test.py
  convert2rhel/unit_tests/actions/report_test.py
  convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/custom_repos_are_valid_test.py
  convert2rhel/unit_tests/actions/system_checks/dbus_test.py
  convert2rhel/unit_tests/actions/system_checks/efi_test.py
  convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/readonly_mounts_test.py
  convert2rhel/unit_tests/actions/system_checks/rhel_compatible_kernel_test.py
  convert2rhel/unit_tests/actions/system_checks/tainted_kmods_test.py
Labels: enhancement

#850 [RHELC-975] Output the pre-assessment as a json file.
  convert2rhel/actions/report.py
  convert2rhel/main.py
  convert2rhel/unit_tests/actions/report_test.py
  convert2rhel/unit_tests/main_test.py
Labels: enhancement

#865 Replaced --disable-submgr with --no-rhsm.
  tests/integration/tier0/destructive/method/custom_repos.py
  tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py
  tests/integration/tier1/destructive/one-kernel-scenario/run_conversion.py
Labels: no-changelog

#856 [RHELC-824] Add remaining distros for the offline conversion test
  plans/tier0.fmf
  plans/tier1.fmf
  tests/integration/tier0/destructive/convert-offline-systems/prepare_system.py
Labels: no-changelog

#858 [RHELC-1000] Change datetime to ISO with timezone to be standardized
  convert2rhel/logger.py
Labels: enhancement

#866 [RHELC-1087] tests/Use manual_trigger in packit.yaml
  .packit.yaml
Labels: no-changelog

#873 Bump to 1.3.2 in main
  convert2rhel/__init__.py
  packaging/convert2rhel.spec
Labels: no-changelog

#864 [RHELC-873] tests/Remove workaround for three kernels installed
  tests/integration/tier1/destructive/system-up-to-date/test_system_up_to_date.py
Labels: no-changelog
