Repository oamg/convert2rhel, pull requests merged in 2023-05, with the labels that each got.

#816 [RHELC-1004] tests/Fix pulp url
  plans/main.fmf
  plans/rerun.fmf
  tests/ansible_collections/main.yml
  tests/ansible_collections/roles/add-custom-repos/rhel7-repos.yml
  tests/ansible_collections/roles/add-custom-repos/rhel8-eus-repos.yml
  tests/ansible_collections/roles/add-custom-repos/rhel8-repos.yml
  tests/ansible_collections/roles/update-ca-trust/tasks/main.yml
  tests/ansible_collections/roles/update-ca-trust/tasks/update-ca-trust.yml
  tests/integration/tier0/custom-repository/files/rhel7.repo
  tests/integration/tier0/custom-repository/files/rhel8-eus.repo
  tests/integration/tier0/custom-repository/files/rhel8.repo
  tests/integration/tier1/one-kernel-scenario/install_one_kernel.py
  tests/integration/tier1/one-kernel-scenario/run_conversion.py
Labels: no-changelog

#827 [RHELC-1008] Update packit.yaml and pre-commit-config.yaml
  .packit.yaml
  .pre-commit-config.yaml
Labels: no-changelog

#830 Fix typo in dnf callback
  convert2rhel/pkgmanager/handlers/dnf/callback.py
  convert2rhel/unit_tests/pkgmanager/handlers/dnf/callback_test.py
Labels: no-changelog

#817 [RHELC-1003] Allow to skip kernel check even if packages are available
  convert2rhel/actions/system_checks/is_loaded_kernel_latest.py
  convert2rhel/checks.py
  convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py
  plans/rerun.fmf
  plans/tier1.fmf
  pytest.ini
  tests/integration/tier1/checks-after-conversion/test_rhel_kernel.py
  tests/integration/tier1/kernel-check-skip/main.fmf
  tests/integration/tier1/kernel-check-skip/test_latest_kernel_check_skip.py
  tests/integration/tier1/one-kernel-scenario/run_conversion.py
Labels: bug-fix

#835 chore: update vscode directory settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: no-changelog

#838 tests/hotfix/Remove parsing .env in conftest
  tests/integration/conftest.py
Labels: no-changelog

#839 [RHELC-1016] Expect release of Oracle Linux 8.8
  plans/main.fmf
  tests/ansible_collections/roles/add-custom-repos/main.yml
  tests/integration/tier0/custom-kernel/test_custom_kernel.py
  tests/integration/tier1/checks-after-conversion/test_release_version.py
  tests/integration/tier1/kernel-boot-files/test_handle_missing_boot_files.py
Labels: no-changelog

#826 [RHELC-901] Allow username and organization in the config file
  config/convert2rhel.ini
  convert2rhel/toolopts.py
  convert2rhel/unit_tests/toolopts_test.py
  tests/integration/tier0/config-file/test_config_file.py
  tests/integration/tier1/config-file/test_config_file.py
Labels: enhancement

#814 [RHELC-781, RHELC-821] Don't require --pool or --auto-attach
  convert2rhel/subscription.py
  convert2rhel/systeminfo.py
  convert2rhel/toolopts.py
  convert2rhel/unit_tests/subscription_test.py
  convert2rhel/unit_tests/systeminfo_test.py
  convert2rhel/utils.py
  pytest.ini
  tests/integration/tier0/rollback-handling/main.fmf
  tests/integration/tier0/rollback-handling/test_rollback_handling.py
  tests/integration/tier0/user-prompt-response/main.fmf
  tests/integration/tier0/user-prompt-response/test_user_prompt_response.py
Labels: enhancement

#833 [RHELC-899] Prevent packages marked for update to reinstall
  convert2rhel/pkgmanager/handlers/dnf/__init__.py
  convert2rhel/pkgmanager/handlers/yum/__init__.py
  convert2rhel/unit_tests/pkgmanager/handlers/dnf/dnf_test.py
  convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py
  plans/tier1.fmf
  pytest.ini
  tests/integration/tier1/single-yum-transaction/main.fmf
  tests/integration/tier1/single-yum-transaction/test_check_for_latest_packages.py
  tests/integration/tier1/system-up-to-date/main.fmf
Labels: bug-fix

#842 Release 1.3.0 Swallowtail
  convert2rhel/__init__.py
  packaging/convert2rhel.spec
Labels: no-changelog

#844 Fix build failure by pre-generating man-pages
  convert2rhel/__init__.py
  man/convert2rhel.8
  packaging/convert2rhel.spec
  setup.py
Labels: bug-fix
