Repository oamg/convert2rhel, pull requests merged in 2023-09, with the labels that each got.

#888 [RHELC-1094] Split report messages into four fields
  .packit.yaml
  convert2rhel/actions/__init__.py
  convert2rhel/actions/pre_ponr_changes/backup_system.py
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/actions/pre_ponr_changes/kernel_modules.py
  convert2rhel/actions/pre_ponr_changes/special_cases.py
  convert2rhel/actions/pre_ponr_changes/subscription.py
  convert2rhel/actions/pre_ponr_changes/transaction.py
  convert2rhel/actions/report.py
  convert2rhel/actions/system_checks/convert2rhel_latest.py
  convert2rhel/actions/system_checks/custom_repos_are_valid.py
  convert2rhel/actions/system_checks/dbus.py
  convert2rhel/actions/system_checks/efi.py
  convert2rhel/actions/system_checks/is_loaded_kernel_latest.py
  convert2rhel/actions/system_checks/package_updates.py
  convert2rhel/actions/system_checks/readonly_mounts.py
  convert2rhel/actions/system_checks/rhel_compatible_kernel.py
  convert2rhel/actions/system_checks/tainted_kmods.py
  convert2rhel/backup.py
  convert2rhel/logger.py
  convert2rhel/pkghandler.py
  convert2rhel/subscription.py
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/actions/actions_test.py
  convert2rhel/unit_tests/actions/data/stage_tests/all_status_actions/test.py
  convert2rhel/unit_tests/actions/data/stage_tests/good_deps_failed_actions/test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/special_cases_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/transaction_test.py
  convert2rhel/unit_tests/actions/report_test.py
  convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/custom_repos_are_valid_test.py
  convert2rhel/unit_tests/actions/system_checks/dbus_test.py
  convert2rhel/unit_tests/actions/system_checks/efi_test.py
  convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
  convert2rhel/unit_tests/actions/system_checks/readonly_mounts_test.py
  convert2rhel/unit_tests/actions/system_checks/rhel_compatible_kernel_test.py
  convert2rhel/unit_tests/actions/system_checks/tainted_kmods_test.py
  convert2rhel/unit_tests/pkghandler_test.py
  convert2rhel/unit_tests/subscription_test.py
  tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
  tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
  tests/integration/tier0/non-destructive/custom-kernel/test_custom_kernel.py
  tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py
  tests/integration/tier0/non-destructive/kernel-modules/test_unsupported_kmod.py
  tests/integration/tier0/non-destructive/oracle-linux-unbreakable-enterprise-kernel/test_oracle_unsupported_uek.py
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
Labels: enhancement, tests-run-all

#879 [RHELC-1107] Schema to validate the pre-conversion assessment json format
  convert2rhel/actions/__init__.py
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/actions/report.py
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/actions/actions_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
  convert2rhel/unit_tests/actions/report_test.py
  convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/efi_test.py
  convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
  schemas/assessment-schema-1.0.json
  tests/integration/common/checks-after-conversion/test_flag_system_as_converted.py
  tests/integration/conftest.py
  tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
Labels: need-integration-tests, no-changelog, tests-run-all

#845 Try official Oracle Linux AWS AMIs
  .packit.yaml
  plans/main.fmf
Labels: no-changelog, tests-run-all

#902 Change level from warning to info for dbus check skip
  convert2rhel/actions/system_checks/dbus.py
  convert2rhel/unit_tests/actions/system_checks/dbus_test.py
Labels: enhancement, tests-skip

#869 [RHELC-1033, RHELC-1036] Make (re-)registering the system optional
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/actions/pre_ponr_changes/subscription.py
  convert2rhel/actions/pre_ponr_changes/transaction.py
  convert2rhel/actions/system_checks/dbus.py
  convert2rhel/backup.py
  convert2rhel/cert.py
  convert2rhel/main.py
  convert2rhel/pkghandler.py
  convert2rhel/subscription.py
  convert2rhel/systeminfo.py
  convert2rhel/toolopts.py
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/transaction_test.py
  convert2rhel/unit_tests/actions/system_checks/dbus_test.py
  convert2rhel/unit_tests/backup_test.py
  convert2rhel/unit_tests/cert_test.py
  convert2rhel/unit_tests/conftest.py
  convert2rhel/unit_tests/main_test.py
  convert2rhel/unit_tests/pkghandler_test.py
  convert2rhel/unit_tests/subscription_test.py
  convert2rhel/unit_tests/toolopts_test.py
  plans/tier0.fmf
  plans/tier1.fmf
  pytest.ini
  tests/integration/common/checks-after-conversion/main.fmf
  tests/integration/common/checks-after-conversion/test_rhel_subman.py
  tests/integration/conftest.py
  tests/integration/main.fmf
  tests/integration/tier0/destructive/method/main.fmf
  tests/integration/tier0/destructive/method/pre_registered.py
  tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
  tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
  tests/integration/tier0/non-destructive/config-file/test_config_file.py
  tests/integration/tier0/non-destructive/rollback-handling/main.fmf
  tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
  tests/integration/tier0/non-destructive/sub-man-rollback/main.fmf
  tests/integration/tier0/non-destructive/subscription-manager/main.fmf
  tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_pre_register.py
  tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_rollback.py
  tests/integration/tier0/non-destructive/user-prompt-response/main.fmf
  tests/integration/tier1/destructive/remove-all-submgr-pkgs/main.fmf
  tests/integration/tier1/destructive/remove-all-submgr-pkgs/test_no_submgr_pkg_installed.py
  tests/integration/tier1/destructive/remove-all-submgr-pkgs/test_submgr_pkg_installed.py
Labels: enhancement, need-integration-tests, tests-run-all

#893 Bump version to 1.4.0
  convert2rhel/__init__.py
  packaging/convert2rhel.spec
Labels: no-changelog, tests-skip

#905 Fix sub-man installation on Alma and Rocky 8
  convert2rhel/subscription.py
Labels: bug-fix, tests-run-all

#904 [RHELC-1099] Move application lock into main.
  convert2rhel/initialize.py
  convert2rhel/main.py
  convert2rhel/unit_tests/initialize_test.py
  convert2rhel/unit_tests/main_test.py
Labels: bug-fix, tests-run-tier0

#906 Bump version to v1.4.1
  convert2rhel/__init__.py
  packaging/convert2rhel.spec
Labels: no-changelog, tests-skip

#907 [RHELC-1155] Move target compose definition in packit.yaml
  .packit.yaml
Labels: no-changelog, tests-run-all

#919 [RHELC-179] Port pkghandler from unittest to pytest.
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/example_test.py
  convert2rhel/unit_tests/pkghandler_test.py
Labels: no-changelog, tests-skip

#925 Include test-coverage-enhancement label
  .github/release.yml
  .github/workflows/enforce_labels.yml
Labels: no-changelog, tests-skip

#923 [RHELC-765, RHELC-766] Add Alma and Rocky Linux test coverage to the CI
  .packit.yaml
  plans/main.fmf
  plans/tier0.fmf
  plans/tier1.fmf
  tests/ansible_collections/main.yml
  tests/ansible_collections/roles/hardcode-eus-version-repos/tasks/alma-86-repos.yml
  tests/ansible_collections/roles/hardcode-eus-version-repos/tasks/main.yml
  tests/ansible_collections/roles/hardcode-eus-version-repos/tasks/rocky-86-repos.yml
  tests/integration/common/checks-after-conversion/test_release_version.py
  tests/integration/conftest.py
  tests/integration/tier0/destructive/convert-offline-systems/prepare_system.py
  tests/integration/tier0/destructive/method/rhsm_non_eus.py
  tests/integration/tier0/destructive/single-yum-transaction/test_check_for_latest_packages.py
  tests/integration/tier0/destructive/single-yum-transaction/test_single_yum_transaction.py
  tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/enable_centos7_extras.yml
  tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/enable_centos8_extras.yml
  tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/main.yml
  tests/integration/tier0/non-destructive/custom-kernel/test_custom_kernel.py
  tests/integration/tier0/non-destructive/kernel-modules/main.fmf
  tests/integration/tier0/non-destructive/latest-kernel-check/test_latest_kernel_check.py
  tests/integration/tier0/non-destructive/oracle-linux-unbreakable-enterprise-kernel/main.fmf
  tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
  tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
  tests/integration/tier1/destructive/detect-bootloader-partition/test_detect_correct_boot_partition.py
  tests/integration/tier1/destructive/kernel-boot-files/test_handle_corrupted_files.py
  tests/integration/tier1/destructive/kernel-boot-files/test_handle_missing_boot_files.py
  tests/integration/tier1/destructive/one-kernel-scenario/main.fmf
  tests/integration/tier1/destructive/removed-pkgs-centos-85/main.fmf
  tests/integration/tier1/destructive/set-locale/use_non_english_language.py
  tests/integration/tier1/destructive/system-up-to-date/install_non_latest_kernel.py
  tests/integration/tier1/destructive/system-up-to-date/test_system_up_to_date.py
Labels: tests-skip, test-coverage-enhancement

#916 [RHELC-1156] Display system packages that are not up to date in alphabetical order
  convert2rhel/actions/system_checks/package_updates.py
  convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
Labels: enhancement, tests-skip

#895 Cosmetic fixes for the SystemInfo
  convert2rhel/systeminfo.py
Labels: no-changelog, tests-run-tier0

#876 [RHELC-1037] Auto-generate manpages
  .github/workflows/generate_manpage.yml
  .github/workflows/release.yml
  scripts/manpage_generation.sh
Labels: documentation, enhancement, tests-run-tier0

#929 Update Renovate to auto-label its PRs
  .github/renovate.json
Labels: no-changelog, tests-skip

#930 [RHELC-1037] fix for typo in generate_manpage github action
  .github/workflows/generate_manpage.yml
Labels: no-changelog, tests-skip

#898 [RHELC-1102] Add CentOS 9 unit tests
  .gitignore
  Containerfiles/centos9.Containerfile
  Makefile
  requirements/centos9.requirements.txt
Labels: enhancement, tests-skip

#938 Add a link to the wiki in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, no-changelog, tests-skip

#936 [RHELC-1150] Move -y option out of parent options
  convert2rhel/toolopts.py
  man/__init__.py
  man/convert2rhel.8
Labels: no-changelog, tests-skip

#945 [RHELC-1055] Change the default message in report
  convert2rhel/actions/__init__.py
  convert2rhel/actions/report.py
  convert2rhel/unit_tests/actions/actions_test.py
  convert2rhel/unit_tests/actions/report_test.py
Labels: enhancement, tests-skip

#932 [RHELC-1166] Playbook to install convert2rhel from cdn-public.redhat.com
  ansible/setup-convert2rhel.yml
Labels: no-changelog, tests-skip

#920 [RHELC-474] Deduplicate mocking classes
  convert2rhel/unit_tests/__init__.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/transaction_test.py
  convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/custom_repos_are_valid_test.py
  convert2rhel/unit_tests/actions/system_checks/efi_test.py
  convert2rhel/unit_tests/actions/system_checks/rhel_compatible_kernel_test.py
  convert2rhel/unit_tests/backup_test.py
  convert2rhel/unit_tests/cert_test.py
  convert2rhel/unit_tests/checks_test.py
  convert2rhel/unit_tests/grub_test.py
  convert2rhel/unit_tests/main_test.py
  convert2rhel/unit_tests/pkghandler_test.py
  convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py
  convert2rhel/unit_tests/redhatrelease_test.py
  convert2rhel/unit_tests/subscription_test.py
  convert2rhel/unit_tests/systeminfo_test.py
  convert2rhel/unit_tests/utils_test.py
  pytest.ini
Labels: no-changelog, tests-skip

#933 [RHELC-1167] tests/Slim down PR test suite
  .github/label-commenter-config.yml
  .github/workflows/enforce_verification_labels.yml
  .packit.yaml
  plans/tier0.fmf
  tests/integration/tier0/non-destructive/application-lock/main.fmf
  tests/integration/tier0/non-destructive/assessment-report/main.fmf
  tests/integration/tier0/non-destructive/basic-sanity-checks/main.fmf
  tests/integration/tier0/non-destructive/config-file/main.fmf
  tests/integration/tier0/non-destructive/cve-2022-1662/main.fmf
  tests/integration/tier0/non-destructive/internet-connection-check/main.fmf
  tests/integration/tier0/non-destructive/kernel-modules/main.fmf
  tests/integration/tier0/non-destructive/logged-command/main.fmf
  tests/integration/tier0/non-destructive/rollback-handling/main.fmf
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf
  tests/integration/tier0/non-destructive/subscription-manager/main.fmf
  tests/integration/tier0/non-destructive/system-release-backup/main.fmf
Labels: no-changelog, tests-run-sanity

#943 [RHELC-1163] Update Skip results to have diagnosis and remediation fields
  convert2rhel/actions/__init__.py
Labels: enhancement, tests-run-tier0
