Repository oamg/convert2rhel, pull requests merged in 2024-06, with the labels that each got.

#1253 chore: add HMS to release notes workflow
  .github/pull_request_template.md
  .github/workflows/release.yml
Labels: no-changelog, tests-skip

#1249 chore: build docs on PR and push to main
  .devcontainer/alma9/alma9-development.Containerfile
  .devcontainer/alma9/devcontainer.json
  .devcontainer/alma9/requirements.txt
  .devcontainer/centos7/requirements.txt
  .github/workflows/main-docs-deploy.yml
  .github/workflows/pr-docs-check.yml
  docs/requirements.txt
Labels: no-changelog, tests-skip

#1240 Apply missing coments from PR#1212
  convert2rhel/backup/subscription.py
  convert2rhel/unit_tests/backup/subscription_test.py
Labels: no-changelog, tests-run-tier0

#1244 [RHELC-1428, RHELC-1366, RHELC-1594] Include 8.10 in tests, introduce CentOS Stream
  .packit.yaml
  plans/main.fmf
  plans/stream.fmf
  plans/tier0.fmf
  plans/tier1.fmf
  tests/ansible_collections/main.yml
  tests/ansible_collections/roles/add-custom-repos/main.yml
  tests/integration/common/checks-after-conversion/test_release_version.py
  tests/integration/conftest.py
  tests/integration/tier0/destructive/conversion-method/test_custom_repos.py
  tests/integration/tier0/destructive/single-yum-transaction/install_dependency_packages.py
  tests/integration/tier0/destructive/single-yum-transaction/test_single_yum_transaction.py
  tests/integration/tier0/non-destructive/duplicate-pkgs/main.fmf
  tests/integration/tier0/non-destructive/kernel/test_custom_kernel.py
  tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
  tests/integration/tier0/non-destructive/system-release-backup/main.fmf
  tests/integration/tier1/destructive/kernel-boot-files/test_handle_corrupted_files.py
  tests/integration/tier1/destructive/kernel-boot-files/test_handle_missing_boot_files.py
  tests/integration/tier1/destructive/kernel-check-skip/install_older_kernel.py
  tests/integration/tier1/destructive/multiple-nic/multiple_nic.py
Labels: tests-skip, test-coverage-enhancement

#1260 Remove leftover analysis environment variable
  convert2rhel/toolopts.py
  convert2rhel/unit_tests/main_test.py
  tests/integration/tier0/non-destructive/rollback-handling/main.fmf
  tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
Labels: no-changelog, tests-run-tier0, merge-after-tests-ok

#1262 chore: fix versioning of Sphinx in GH Actions
  .devcontainer/alma9/requirements.txt
  .github/workflows/main-docs-deploy.yml
  .github/workflows/pr-docs-check.yml
  docs/Makefile
  docs/requirements.txt
Labels: no-changelog, tests-skip

#1276 Fix exit codes comments
  convert2rhel/main.py
Labels: no-changelog, tests-skip

#1274 chore: improve sphinx workflow with composite action
  .github/workflows/main-docs-deploy.yml
  Containerfiles/centos9.Containerfile
  docs/source/_static/.gitkeep
  docs/source/conf.py
Labels: no-changelog, tests-skip
