Repository oamg/convert2rhel, pull requests merged in 2024-10, with the labels that each got.

#1393 chore: Update image builds with new tags
  .github/workflows/build_images.yml
Labels: no-changelog, tests-skip

#1354 [RHELC-1615] CentOS Stream 9 test coverage
  .packit.yaml
  convert2rhel/data/9/x86_64/configs/centos-9-x86_64.cfg
  plans/main.fmf
  plans/stream.fmf
  tests/integration/common/checks-after-conversion/main.fmf
  tests/integration/common/checks-after-conversion/test_release_version.py
  tests/integration/tier0/destructive/single-yum-transaction/test_single_yum_transaction.py
  tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/main.yml
  tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
  tests/integration/tier0/non-destructive/kernel-modules/main.fmf
  tests/integration/tier0/non-destructive/modified-releasever/test_modified_releasever.py
  tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
Labels: tests-skip, test-coverage-enhancement

#1265 [RHELC-788] Implement integration test error after ponr
  plans/tier1.fmf
  tests/integration/tier0/destructive/conversion-method/test_config_file.py
  tests/integration/tier1/destructive/error-after-ponr/main.fmf
  tests/integration/tier1/destructive/error-after-ponr/test_error_after_ponr.py
Labels: no-changelog, tests-run-sanity

#1396 chore: update CODEOWNERS to reflect latest status
  .github/CODEOWNERS
Labels: no-changelog, tests-skip

#1288 [RHELC-1747] Use enablerepo instead of no_rhsm to check custom repos
  convert2rhel/actions/pre_ponr_changes/custom_repos_are_valid.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/custom_repos_are_valid_test.py
Labels: bug-fix, tests-run-sanity

#1389 [RHELC-1677] Fix missing repository directory
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
  tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
Labels: bug-fix, tests-run-sanity

#1397 [RHELC-1598] Add EL9 repofile url to convert2rhel latest check
  convert2rhel/actions/system_checks/convert2rhel_latest.py
  convert2rhel/repo.py
Labels: enhancement, tests-run-sanity

#1402 chore: update and improve workflows
  .github/label-commenter-config.yml
  .github/pull_request_template.md
  .github/release.yml
  .github/renovate.json
  .github/workflows/build-rpm.yml
  .github/workflows/build_images.yml
  .github/workflows/codeql.yml
  .github/workflows/enforce_labels.yml
  .github/workflows/jira-links.yml
Labels: no-changelog, tests-skip

#1405 chore: Enforce label to ignore right users
  .github/workflows/enforce_labels.yml
  .github/workflows/enforce_verification_labels.yml
Labels: skip/changelog, tests/skip, kind/infra

#1404 chore: RPM build workflow to fetch correct tags
  .github/workflows/build-rpm.yml
  Makefile
Labels: skip/changelog, tests/skip, kind/infra

#1406 chore: Fix workflow ghcr.io authentication
  .github/workflows/build-rpm.yml
Labels: skip/changelog, tests/skip, kind/infra

#1407 chore: workflow to upload only modified files
  .github/workflows/build-rpm.yml
Labels: skip/changelog, tests/skip, kind/infra

#1410 chore:Disable the tier0 a and tier1 plans for Stream 9
  plans/tier0.fmf
  plans/tier1.fmf
Labels: skip/changelog, tests/skip, kind/tests

#1395 [RHELC-1725] Update rhsm custom facts
  convert2rhel/breadcrumbs.py
  convert2rhel/unit_tests/breadcrumbs_test.py
Labels: kind/feature, tests/sanity

#1387 [RHELC-1740] Use toolopts instead of env var
  convert2rhel/actions/post_conversion/hostmetering.py
  convert2rhel/actions/pre_ponr_changes/backup_system.py
  convert2rhel/actions/pre_ponr_changes/kernel_modules.py
  convert2rhel/actions/system_checks/convert2rhel_latest.py
  convert2rhel/actions/system_checks/is_loaded_kernel_latest.py
  convert2rhel/actions/system_checks/package_updates.py
  convert2rhel/actions/system_checks/tainted_kmods.py
  convert2rhel/toolopts/__init__.py
  convert2rhel/unit_tests/actions/post_conversion/hostmetering_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py
  convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py
  convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
  convert2rhel/unit_tests/actions/system_checks/tainted_kmods_test.py
  convert2rhel/unit_tests/conftest.py
  convert2rhel/unit_tests/utils/utils_test.py
  convert2rhel/utils/__init__.py
Labels: kind/feature, tests/sanity

#1373 refactor: Improved logger usage
  convert2rhel/actions/__init__.py
  convert2rhel/actions/conversion/list_non_red_hat_pkgs_left.py
  convert2rhel/actions/conversion/lock_releasever.py
  convert2rhel/actions/conversion/pkg_manager_config.py
  convert2rhel/actions/conversion/preserve_only_rhel_kernel.py
  convert2rhel/actions/conversion/set_efi_config.py
  convert2rhel/actions/conversion/transaction.py
  convert2rhel/actions/post_conversion/breadcrumbs_finish_collection.py
  convert2rhel/actions/post_conversion/hostmetering.py
  convert2rhel/actions/post_conversion/kernel_boot_files.py
  convert2rhel/actions/post_conversion/modified_rpm_files_diff.py
  convert2rhel/actions/post_conversion/remove_tmp_dir.py
  convert2rhel/actions/post_conversion/rhsm_custom_facts_config.py
  convert2rhel/actions/post_conversion/update_grub.py
  convert2rhel/actions/pre_ponr_changes/backup_system.py
  convert2rhel/actions/pre_ponr_changes/custom_repos_are_valid.py
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/actions/pre_ponr_changes/kernel_modules.py
  convert2rhel/actions/pre_ponr_changes/special_cases.py
  convert2rhel/actions/pre_ponr_changes/subscription.py
  convert2rhel/actions/pre_ponr_changes/transaction.py
  convert2rhel/actions/system_checks/check_firewalld_availability.py
  convert2rhel/actions/system_checks/convert2rhel_latest.py
  convert2rhel/actions/system_checks/dbus.py
  convert2rhel/actions/system_checks/duplicate_packages.py
  convert2rhel/actions/system_checks/efi.py
  convert2rhel/actions/system_checks/grub_validity.py
  convert2rhel/actions/system_checks/is_loaded_kernel_latest.py
  convert2rhel/actions/system_checks/package_updates.py
  convert2rhel/actions/system_checks/readonly_mounts.py
  convert2rhel/actions/system_checks/rhel_compatible_kernel.py
  convert2rhel/actions/system_checks/tainted_kmods.py
  convert2rhel/backup/certs.py
  convert2rhel/backup/files.py
  convert2rhel/backup/packages.py
  convert2rhel/backup/subscription.py
  convert2rhel/logger.py
  convert2rhel/main.py
  convert2rhel/phase.py
  convert2rhel/unit_tests/actions/post_conversion/breadcrumbs_finish_collection_test.py
  convert2rhel/unit_tests/backup/files_test.py
  convert2rhel/unit_tests/main_test.py
  tests/integration/tier1/destructive/kernel-boot-files/test_handle_corrupted_files.py
  tests/integration/tier1/destructive/kernel-boot-files/test_handle_missing_boot_files.py
Labels: tests/sanity, merge-after-tests-ok, kind/refactor

#1235 [RHELC-1169] Add a log message to check if the user has a back up of their system
  convert2rhel/breadcrumbs.py
  convert2rhel/main.py
  convert2rhel/unit_tests/breadcrumbs_test.py
  convert2rhel/unit_tests/main_test.py
  tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
  tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
  tests/integration/tier0/non-destructive/kernel-modules/test_unsupported_kmod.py
  tests/integration/tier0/non-destructive/kernel/test_custom_kernel.py
  tests/integration/tier0/non-destructive/kernel/test_kernel_check_verification.py
  tests/integration/tier0/non-destructive/logged-command/test_logged_command.py
  tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
  tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
  tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_pre_register.py
  tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
Labels: kind/feature, tests/tier0

#1416 hotfix/Bump release
  packaging/convert2rhel.spec
Labels: skip/changelog, tests/skip, kind/infra

#1417 chore(workflows): Autotag to upload rpms
  .github/renovate.json
  .github/workflows/build-rpm.yml
  .github/workflows/jira-links.yml
Labels: skip/changelog, tests/skip, kind/infra

#1359 [RHELC-1711] Except UnicodeDecodeError when parsing initramfs
  convert2rhel/checks.py
  convert2rhel/unit_tests/checks_test.py
  plans/tier1.fmf
Labels: kind/bug-fix, tests/skip
