Repository oamg/convert2rhel, pull requests merged in 2025-04, with the labels that each got.

#1297 [RHELC-1635] State action in special pkg removal report msgs
  convert2rhel/actions/pre_ponr_changes/handle_packages.py
  convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
Labels: kind/feature, tests/sanity

#1463 Disable Oracle Linux 7.9 test pipelines
  .packit.yaml
Labels: skip/changelog, tests/skip, kind/infra

#1462 Update Python version in manpage workflow to 3.13
  .github/workflows/generate_manpage.yml
Labels: kind/dependencies, skip/changelog, tests/skip

#1464 Add VS Code workspace file to .gitignore
  .gitignore
Labels: skip/changelog, tests/skip, kind/infra
